databases:
  - name: rails7_sample_staging
    databaseName: rails7_sample_staging
    user: rails7_sample
    region: singapore

services:
  - type: web
    name: rails7-sample-staging
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7_sample_staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
